import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ImagePlus, X, Heart } from 'lucide-react';
import { motion } from 'motion/react';
import { birthday } from './config';
export function Photo({src,caption,number,large=false}:{src:string;caption:string;number:string;large?:boolean}){
 const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);
 return src&&!failed?<img src={src} alt={caption} loading={large?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>:<div className="photo-placeholder"><span className="photo-corner">✧</span><ImagePlus size={large?40:27} strokeWidth={1}/><span>{failed?'Photo unavailable':number}</span><small>{failed?'Check the image path':'a place for our memory'}</small><Heart className="placeholder-heart" size={18} strokeWidth={1}/></div>;
}
export default function Memories({onContinue,reduced}:{onContinue:()=>void;reduced:boolean}){
 const [selected,setSelected]=useState<number|null>(null);const dialog=useRef<HTMLDialogElement>(null);const origin=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{if(selected!==null){dialog.current?.showModal();const prior=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prior;};}else if(dialog.current?.open)dialog.current.close();},[selected]);
 function close(){setSelected(null);origin.current?.focus();}
 return <section className="memory-section"><div className="section-heading"><p className="eyebrow">LITTLE MOMENTS, BIG FEELINGS</p><h1>A Few Memories <em>With You <span>♡</span></em></h1><p className="lead">Every picture holds a little piece of our story.</p></div><div className="scrapbook" onPointerMove={e=>{if(reduced||e.pointerType!=='mouse')return;const rect=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--drift',`${(e.clientX-rect.left-rect.width/2)*.007}px`);}} onPointerLeave={e=>e.currentTarget.style.setProperty('--drift','0px')}><span className="scrapbook-note handwritten">my favorite kind of throwback ↴</span>{birthday.memories.map((memory,i)=><motion.button key={i} className={`polaroid polaroid-${i+1}`} initial={{opacity:0,y:reduced?0:20}} animate={{opacity:1,y:0}} transition={{delay:reduced?0:i*.14}} aria-label={`Open memory ${i+1}: ${memory.caption}`} onClick={e=>{origin.current=e.currentTarget;setSelected(i);}}><span className="tape"/><div className="photo-wrap"><Photo src={memory.photo} caption={memory.caption} number={`[PHOTO_${i+1}]`}/></div><span className="photo-caption handwritten">{memory.caption}</span><span className="photo-label">{memory.label}</span></motion.button>)}<span className="scrapbook-doodle handwritten">us, being us. ♡</span></div><p className="memory-hint">Tap a photo to linger a little longer.</p><button className="primary" onClick={onContinue}>Okay, One More Surprise <ArrowRight size={18}/></button><dialog ref={dialog} className="lightbox" aria-label="Enlarged memory" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="lightbox-content"><button className="icon-button close-lightbox" aria-label="Close memory" onClick={close}><X/></button>{selected!==null&&<><div className="lightbox-photo"><Photo src={birthday.memories[selected].photo} caption={birthday.memories[selected].caption} number={`[PHOTO_${selected+1}]`} large/></div><p className="handwritten">{birthday.memories[selected].caption}</p><span>{birthday.memories[selected].label}</span></>}</div></dialog></section>;
}
