import { Component, Suspense, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Html, Line } from '@react-three/drei';
import * as THREE from 'three';

export const colors=['#e9a6bd','#bfa9db','#f3c19f','#dfa0b4','#c6b8e6','#f0c5b7','#ce9cac'];
const positions:[number,number,number][]=[[-1.75,1.05,-.4],[-.15,1.85,-.6],[1.55,1.1,-.2],[-.75,.05,.35],[1.35,-.75,.6],[-1.8,-1.3,.4],[0,-1.75,.8]];
type Props={kind:'balloons'|'hearts'|'cake';active?:boolean;collected?:number[];onCollect?:(id:number)=>void;blown?:boolean;cut?:boolean;reduced:boolean};
class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
function supportsWebGL(){try{const canvas=document.createElement('canvas');const gl=canvas.getContext('webgl2');if(!gl)return false;gl.getExtension('WEBGL_lose_context')?.loseContext();return true;}catch{return false;}}
function Floater({id,position,reduced,children}:{id:number;position:[number,number,number];reduced:boolean;children:ReactNode}){
 const ref=useRef<THREE.Group>(null);
 useFrame(({clock})=>{if(!ref.current||reduced)return;const t=clock.elapsedTime;ref.current.position.y=position[1]+Math.sin(t*.65+id*1.7)*.14;ref.current.rotation.z=Math.sin(t*.45+id)*.055;});
 return <group ref={ref} position={position}>{children}</group>;
}
function Balloon({id,active,onCollect,reduced}:{id:number;active:boolean;onCollect?:(id:number)=>void;reduced:boolean}){
 const curve=useMemo(()=>Array.from({length:30},(_,i)=>{const y=-.86-i*.058;return new THREE.Vector3(Math.sin(i*.16+id)*.07,y,0);}),[id]);
 return <Floater id={id} position={positions[id]} reduced={reduced}><mesh scale={[.64,.84,.6]} rotation={[0,0,(id-3)*.055]} onPointerDown={active?e=>{e.stopPropagation();onCollect?.(id);}:undefined} onPointerOver={active?()=>{document.body.style.cursor='pointer';}:undefined} onPointerOut={active?()=>{document.body.style.cursor='';}:undefined}><sphereGeometry args={[1,32,24]}/><meshPhysicalMaterial color={colors[id]} roughness={.24} metalness={.05} clearcoat={.8} clearcoatRoughness={.22}/></mesh><mesh position={[0,-.86,0]} rotation={[0,0,Math.PI]}><coneGeometry args={[.065,.12,12]}/><meshStandardMaterial color={colors[id]}/></mesh><Line points={curve} color="#a78a8a" lineWidth={.7}/>{active&&<Html center zIndexRange={[5,1]}><button className="object-target balloon-target" aria-label={`Pop balloon ${id+1}`} onClick={()=>onCollect?.(id)} /></Html>}</Floater>;
}
function HeartObject({id,onCollect,reduced}:{id:number;onCollect?:(id:number)=>void;reduced:boolean}){
 const shape=useMemo(()=>{const s=new THREE.Shape();s.moveTo(0,-.5);s.bezierCurveTo(-.2,-.3,-.7,.05,-.64,.37);s.bezierCurveTo(-.58,.75,-.15,.8,0,.45);s.bezierCurveTo(.15,.8,.58,.75,.64,.37);s.bezierCurveTo(.7,.05,.2,-.3,0,-.5);return s;},[]);
 const p:[number,number,number]=[[-1.8,.25,1.7,-1,1.1][id%5],[1.3,.3,1.3,-1.3,-1.1][id%5],0];
 return <Floater id={id} position={p} reduced={reduced}><mesh rotation={[0,(id%2?1:-1)*.22,-.12]} onPointerDown={e=>{e.stopPropagation();onCollect?.(id);}} onPointerOver={()=>{document.body.style.cursor='pointer';}} onPointerOut={()=>{document.body.style.cursor='';}}><extrudeGeometry args={[shape,{depth:.2,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.12,bevelThickness:.13,curveSegments:20}]}/><meshPhysicalMaterial color={['#d97696','#bcabd7','#e8a7b8'][id%3]} roughness={.25} clearcoat={.65}/></mesh><Html center zIndexRange={[5,1]}><button className="object-target heart-target" aria-label={`Collect heart ${id+1}`} onClick={()=>onCollect?.(id)}/></Html></Floater>;
}
function Candle({x,z,index,blown,reduced}:{x:number;z:number;index:number;blown:boolean;reduced:boolean}){
 const flame=useRef<THREE.Mesh>(null);const light=useRef<THREE.PointLight>(null);const smoke=useRef<THREE.Mesh>(null);const elapsed=useRef(0);
 useEffect(()=>{elapsed.current=0;},[blown]);
 useFrame(({clock},delta)=>{elapsed.current+=delta;const fade=blown?Math.max(0,1-(elapsed.current-index*.22)*3):1;const flicker=reduced?1:1+Math.sin(clock.elapsedTime*12+index)*.08;if(flame.current){flame.current.scale.set(.085*fade,.18*fade*flicker,.085*fade);flame.current.visible=fade>0;}if(light.current)light.current.intensity=fade*1.4;if(smoke.current){const t=elapsed.current-index*.22-.35;smoke.current.visible=blown&&t>0&&t<2.4;smoke.current.position.y=.95+Math.max(0,t)*.35;smoke.current.scale.setScalar(.08+Math.max(0,t)*.07);(smoke.current.material as THREE.MeshBasicMaterial).opacity=Math.max(0,.3-t*.13);}});
 return <group position={[x,.52,z]}><mesh position={[0,.3,0]}><cylinderGeometry args={[.064,.064,.6,16]}/><meshStandardMaterial color={index%2?'#ad8cc7':'#e29cb1'}/></mesh>{[.1,.25,.4,.55].map(y=><mesh key={y} position={[0,y,0]}><torusGeometry args={[.065,.009,5,16]}/><meshStandardMaterial color="#fff8f0"/></mesh>)}<mesh position={[0,.64,0]}><cylinderGeometry args={[.014,.014,.09,6]}/><meshStandardMaterial color="#674842"/></mesh><mesh ref={flame} position={[0,.81,0]} scale={[.085,.18,.085]}><sphereGeometry args={[1,16,12]}/><meshBasicMaterial color="#ffd183"/></mesh><pointLight ref={light} position={[0,.83,.1]} color="#ffd28c" intensity={1.4} distance={2}/><mesh ref={smoke} visible={false}><sphereGeometry args={[1,10,8]}/><meshBasicMaterial color="#a79a9c" transparent opacity={.25} depthWrite={false}/></mesh></group>;
}
function Cake({blown,cut,reduced}:{blown:boolean;cut:boolean;reduced:boolean}){
 const slice=useRef<THREE.Group>(null);const whole=useRef<THREE.Group>(null);
 useFrame((_,delta)=>{if(slice.current){const factor=reduced?1:1-Math.exp(-delta*4);slice.current.position.x=THREE.MathUtils.lerp(slice.current.position.x,cut?.4:0,factor);slice.current.position.z=THREE.MathUtils.lerp(slice.current.position.z,cut?.8:0,factor);}if(whole.current){const target=cut?1.06:1;whole.current.scale.lerp(new THREE.Vector3(target,target,target),reduced?1:1-Math.exp(-delta*3));}});
 const wedge=.72;
 function layers(start:number,length:number){return <><mesh position={[0,-.34,0]}><cylinderGeometry args={[1.48,1.48,1.32,64,1,false,start,length]}/><meshStandardMaterial color="#e9abc0" roughness={.53}/></mesh><mesh position={[0,-.34,0]}><cylinderGeometry args={[1.487,1.487,.09,64,1,false,start,length]}/><meshStandardMaterial color="#f7e5d5"/></mesh><mesh position={[0,.36,0]}><cylinderGeometry args={[1.51,1.51,.18,64,1,false,start,length]}/><meshStandardMaterial color="#fff0df" roughness={.45}/></mesh></>;}
 return <group ref={whole} rotation={[.29,-.68,0]} position={[0,-.2,0]}><mesh position={[0,-1.1,0]}><cylinderGeometry args={[1.95,1.8,.13,64]}/><meshStandardMaterial color="#eee0f1" roughness={.32}/></mesh><group>{layers(wedge,Math.PI*2-wedge)}</group><group ref={slice}>{layers(0,wedge)}</group>{Array.from({length:32},(_,i)=>{const a=wedge+(Math.PI*2-wedge)*i/31;return <mesh key={i} position={[Math.sin(a)*1.45,.23,Math.cos(a)*1.45]} scale={[.16,.2+(i%3)*.03,.16]}><sphereGeometry args={[1,12,10]}/><meshStandardMaterial color="#fff0df" roughness={.5}/></mesh>;})}{Array.from({length:35},(_,i)=>{const a=i*2.399;const r=.36+((i*7)%13)/13;return <mesh key={i} position={[Math.sin(a)*r,.47,Math.cos(a)*r]} rotation={[0,a,Math.PI/2]}><capsuleGeometry args={[.018,.07,2,6]}/><meshStandardMaterial color={colors[i%colors.length]}/></mesh>;})}{[-.75,0,.75].map((x,i)=><Candle key={i} x={x} z={i===1?-.3:0} index={i} blown={blown} reduced={reduced}/>)}<mesh rotation={[-Math.PI/2,0,0]} position={[0,-1.2,0]}><circleGeometry args={[2.15,48]}/><meshBasicMaterial color="#c4a3b5" transparent opacity={.12}/></mesh></group>;
}
function World(p:Props){const {viewport}=useThree();const scale=Math.min(viewport.width/5.4,viewport.height/6.6);const ids=p.collected??[];const visibleHearts=Array.from({length:5},(_,i)=>ids.includes(i)?i+5:i).filter(i=>!ids.includes(i));return <group scale={scale}><ambientLight intensity={1.5}/><directionalLight position={[-3,5,5]} intensity={3.2} color="#fff5eb"/><directionalLight position={[4,0,2]} intensity={.7} color="#e1d3fa"/>{p.kind==='balloons'&&positions.map((_,id)=>!ids.includes(id)&&<Balloon key={id} id={id} active={!!p.active} onCollect={p.onCollect} reduced={p.reduced}/>)}{p.kind==='hearts'&&visibleHearts.map(id=><HeartObject key={id} id={id} onCollect={p.onCollect} reduced={p.reduced}/>)}{p.kind==='cake'&&<Cake blown={!!p.blown} cut={!!p.cut} reduced={p.reduced}/>}</group>;}
function Fallback(p:Props){const ids=p.collected??[];if(p.kind==='cake')return <div className={`fallback-cake ${p.cut?'is-cut':''}`} role="img" aria-label={p.blown?'Birthday cake with extinguished candles':'Birthday cake with three lit candles'}><div className="fallback-candles">{[0,1,2].map(i=><span key={i}>{!p.blown&&<i/>}</span>)}</div><div className="cake-top"/><div className="cake-base"/><div className="cake-plate"/></div>;const all=p.kind==='balloons'?7:10;return <div className={`fallback-objects ${p.kind}`}>{Array.from({length:all},(_,i)=>!ids.includes(i)&&<button key={i} disabled={!p.active} className={p.kind==='balloons'?'fallback-balloon':'fallback-heart'} style={{'--color':colors[i%7]} as React.CSSProperties} aria-label={p.kind==='balloons'?`Pop balloon ${i+1}`:`Collect heart ${i+1}`} onClick={()=>p.onCollect?.(i)}>{p.kind==='hearts'?'♥':''}</button>)}</div>;}
export default function Scene(p:Props){const [webgl]=useState(supportsWebGL);const [lost,setLost]=useState(false);const fallback=<Fallback {...p}/>;return <div className="three-scene">{webgl&&!lost?<SceneBoundary fallback={fallback}><Suspense fallback={<div className="scene-loading">Gathering a little magic…</div>}><Canvas orthographic camera={{position:[0,0,10],zoom:65,near:.1,far:100}} dpr={[1,1.5]} gl={{antialias:true,alpha:true,powerPreference:'low-power'}} onCreated={({gl})=>{gl.domElement.addEventListener('webglcontextlost',()=>setLost(true),{once:true});}}><World {...p}/></Canvas></Suspense></SceneBoundary>:fallback}</div>;}
